spring.application.name=todoApp

spring.mongodb.uri=mongodb+srv://sudharsan:srm123456@cluster0.uygwfmb.mongodb.net/TodoApp?retryWrites=true&w=majority

spring.mongodb.database=TodoApp
logging.level.org.mongodb.driver.cluster=DEBUG

